#!/usr/bin/env python3
"""Generate the two controlled local-AI M10 research sources.

The canonical source always preserves production owner blockers. The no-owner
variant is generated by three exact, fail-closed substitutions so it cannot
accidentally disable broker, margin, risk, spread, timing, no-breakout, SL, or
execution protections.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "XAUUSD_AI_Sniper_EA.mq5"
OUTPUT = ROOT / "research" / "local_ai_m10"


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) != 1:
        raise RuntimeError(f"expected exactly one controlled marker, found {text.count(old)}: {old[:100]!r}")
    return text.replace(old, new, 1)


def main() -> None:
    canonical = SOURCE.read_text(encoding="utf-8")
    no_owner = replace_once(
        canonical,
        "InpResearchOwnerBlockersEnabled = true;",
        "InpResearchOwnerBlockersEnabled = false;",
    )
    no_owner = replace_once(
        no_owner,
        "{\n   XAU_PermanentM10PolicyFacts facts;\n   XAU_ResolvePermanentM10PolicyFacts",
        "{\n"
        "   if(!InpResearchOwnerBlockersEnabled)\n"
        "   {\n"
        "      reason=\"\";\n"
        "      PrintFormat(\"RESEARCH_OWNER_BLOCKERS_DISABLED | phase=%s source=%s setup=%s grade=%s | "
        "disabledScope=PERMANENT_ENUMERATED_LIST | otherGatesPreserved=true\",phase,source,candidateSetup,grade);\n"
        "      return true;\n"
        "   }\n"
        "   XAU_PermanentM10PolicyFacts facts;\n"
        "   XAU_ResolvePermanentM10PolicyFacts",
    )
    no_owner = replace_once(
        no_owner,
        "if(ownerLocationIsExcellent || ownerLocationIsLate)",
        "if(InpResearchOwnerBlockersEnabled && (ownerLocationIsExcellent || ownerLocationIsLate))",
    )
    no_owner = replace_once(
        no_owner,
        "void XAU_OwnerLocationFinalAssertion(int direction, string source)\n{\n   ENUM_XAU_LOCATION_QUALITY loc",
        "void XAU_OwnerLocationFinalAssertion(int direction, string source)\n"
        "{\n"
        "   if(!InpResearchOwnerBlockersEnabled) return;\n"
        "   ENUM_XAU_LOCATION_QUALITY loc",
    )

    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "XauCloud_M10_LOCAL_AI_WITH_OWNER_BLOCKERS.mq5").write_text(canonical, encoding="utf-8")
    (OUTPUT / "XauCloud_M10_LOCAL_AI_NO_OWNER_BLOCKERS.mq5").write_text(no_owner, encoding="utf-8")
    print("generated controlled local-AI M10 variants")


if __name__ == "__main__":
    main()
