import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { getDb } from "../../db.js";
import { requireGptAction } from "./gptEmailActions.js";
import { publicDraft } from "../../services/adminEmailCampaign.js";
import { readinessSnapshot } from "../../services/readiness.js";
import { recentDiagnostics, diagnosticByRequest } from "../../services/diagnostics.js";
import {
  auditAdminAction, consumeAdminConfirmation, emailDeliverySummary, ensureAdminOpsInfrastructure, idempotentResult,
  issueAdminConfirmation, listTransactionalTemplates, maskEmail, replayData, requireActionPermission, releaseSummary,
  sanitizeLicense, sanitizeOrder, sanitizeUser, saveIdempotentResult, transactionalTemplate, TransactionalTemplateDraftSchema,
  TransactionalTemplateIdSchema, renderTransactional,
} from "../../services/adminOpsControl.js";
import { sendPinEmail } from "../../services/paymentEmails.js";
import { sendAccountNoticeEmail } from "../../services/accountLifecycleEmails.js";
import { adminListCertificates, adminRevokeCertificate } from "../../services/academyCertificates.js";
import { loadEaReleaseManifest } from "../../services/releaseManifest.js";
import { getSettings } from "../../services/settings.js";

const Id = z.object({ id: z.string().min(1).max(160) });
const UserLookup = z.object({ q: z.string().min(1).max(320).optional(), status: z.enum(["active","disabled","all"]).optional().default("all"), limit: z.coerce.number().int().min(1).max(100).optional().default(25) });
const OrderLookup = z.object({ q: z.string().max(320).optional(), status: z.string().max(80).optional(), limit: z.coerce.number().int().min(1).max(100).optional().default(25) });
const Confirm = z.object({ confirmation_token: z.string().min(20).max(300), idempotency_key: z.string().min(8).max(128).regex(/^[A-Za-z0-9._:-]+$/) });
const Reason = z.object({ reason: z.string().min(2).max(500) });
const Transfer = z.object({ new_email: z.string().email().max(320), reason: z.string().min(2).max(500) });
const TemplatePreview = z.object({ sample_context: z.record(z.string(), z.string().max(1000)).optional().default({}) });
const TicketDraft = z.object({ body: z.string().min(1).max(10000) });
const AccountNotice = z.object({ subject: z.string().min(1).max(300).refine((v) => !/[\r\n]/.test(v)), message: z.string().min(1).max(5000) });

function fail(reply: FastifyReply, error: unknown) {
  const status = Number((error as { statusCode?: unknown })?.statusCode ?? 500);
  const message = error instanceof Error ? error.message : "Action failed.";
  return reply.code(status >= 400 && status < 600 ? status : 500).send({ detail: message });
}
function cfg(action: string, permission: string) { return { config: { gptActionName: action, permission } }; }
function redactConfig(settings: Record<string, unknown>) {
  const out: Record<string, unknown> = {};
  for (const [k,v] of Object.entries(settings)) if (!/password|secret|token|private|api[_-]?key/i.test(k)) out[k] = v;
  return out;
}

export async function registerAdminOpsActionRoutes(app: FastifyInstance): Promise<void> {
  app.addHook("preHandler", requireGptAction);
  app.addHook("onResponse", async (request, reply) => {
    const c = request.routeOptions.config as unknown as Record<string, unknown>;
    const action = String(c["gptActionName"] ?? request.routeOptions.url);
    try { await auditAdminAction(request, action, request.url.split("?",1)[0] ?? "", reply.statusCode < 400 ? "success" : "error", { status_code: reply.statusCode, permission: c["permission"] ?? "" }); } catch {}
  });

  app.get("/admin/actions/ops/capabilities", cfg("getAdminCapabilities","admin.read"), async () => {
    requireActionPermission("admin.read");
    return { model: "controlled_admin_actions", rules: { arbitrary_database: false, shell: false, filesystem: false, unrestricted_http: false, consequential_requires_confirmation: true }, groups: ["users","licenses","orders","transactional_email","diagnostics","replays","releases","command_center","support","analytics","website","notifications"] };
  });

  app.get("/admin/actions/ops/users", cfg("searchUsers","admin.read"), async (request) => {
    requireActionPermission("admin.read"); const q = UserLookup.parse(request.query); const filter: Record<string, unknown> = {};
    if (q.q) filter["$or"] = [{ email: { $regex: q.q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"), $options:"i" } }, { full_name: { $regex: q.q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"), $options:"i" } }];
    if (q.status === "active") filter["disabled_at"] = { $exists: false }; if (q.status === "disabled") filter["disabled_at"] = { $exists: true };
    const rows = await getDb().collection("cloud_users").find(filter,{projection:{password_hash:0,_id:0}}).sort({created_at:-1}).limit(q.limit).toArray();
    return { total_returned: rows.length, users: rows.map(r => sanitizeUser(r as Record<string,unknown>)) };
  });
  app.get("/admin/actions/ops/users/:id", cfg("getUser","admin.read"), async (request, reply) => {
    requireActionPermission("admin.read"); const {id}=Id.parse(request.params); const row=await getDb().collection("cloud_users").findOne({$or:[{id},{email:id.toLowerCase()}]},{projection:{password_hash:0,_id:0}}); if(!row)return reply.code(404).send({detail:"User not found."});
    const [lic, logins, activity] = await Promise.all([
      getDb().collection("pin_licenses").findOne({buyer_email:String(row["email"]??"").toLowerCase()},{projection:{_id:0}}),
      getDb().collection("login_audit_log").find({email:String(row["email"]??"").toLowerCase(),role:"cloud_user"},{projection:{_id:0,ip:0}}).sort({ts:-1}).limit(20).toArray(),
      getDb().collection("cloud_bot_activity").countDocuments({user_id:String(row["id"]??"")}),
    ]);
    return { user:sanitizeUser(row as Record<string,unknown>), profile:{country:row["country"]??""}, status:row["disabled_at"]?"disabled":"active", linked_license:lic?sanitizeLicense(lic as Record<string,unknown>):null, recent_logins:logins, activity_summary:{bot_activity_events:activity}, sessions:{tracking:"jwt_cookie_sessions_are_not_persisted_server_side", reset_supported:false} };
  });

  app.post("/admin/actions/ops/users/:id/disable/prepare", cfg("prepareDisableUser","admin.users.write"), async (request, reply)=>{ try { requireActionPermission("admin.users.write"); const {id}=Id.parse(request.params); const body=Reason.parse(request.body); const row=await getDb().collection("cloud_users").findOne({id},{projection:{_id:0,password_hash:0}}); if(!row)return reply.code(404).send({detail:"User not found."}); return {target:sanitizeUser(row as Record<string,unknown>), reason:body.reason, ...(await issueAdminConfirmation("user",id,"disable",{id,reason:body.reason,updated_at:row["updated_at"]??null}))}; } catch(e){return fail(reply,e);} });
  app.post("/admin/actions/ops/users/:id/disable", cfg("disableUser","admin.users.write"), async (request,reply)=>{ try { requireActionPermission("admin.users.write"); const {id}=Id.parse(request.params); const req=Confirm.merge(Reason).parse(request.body); const old=await idempotentResult(req.idempotency_key,"disableUser"); if(old)return {...old,duplicate:true}; const row=await getDb().collection("cloud_users").findOne({id},{projection:{_id:0,password_hash:0}}); if(!row)return reply.code(404).send({detail:"User not found."}); await consumeAdminConfirmation(req.confirmation_token,"user",id,"disable",{id,reason:req.reason,updated_at:row["updated_at"]??null}); const at=new Date().toISOString(); await getDb().collection("cloud_users").updateOne({id},{$set:{disabled_at:at,disabled_reason:req.reason,updated_at:at}}); const result={disabled:true,user_id:id,at}; await saveIdempotentResult(req.idempotency_key,"disableUser",result); return result; } catch(e){return fail(reply,e);} });
  app.post("/admin/actions/ops/users/:id/enable/prepare", cfg("prepareEnableUser","admin.users.write"), async (request,reply)=>{ try{requireActionPermission("admin.users.write");const{id}=Id.parse(request.params);const row=await getDb().collection("cloud_users").findOne({id},{projection:{_id:0,password_hash:0}});if(!row)return reply.code(404).send({detail:"User not found."});return {target:sanitizeUser(row as Record<string,unknown>),...(await issueAdminConfirmation("user",id,"enable",{id,disabled_at:row["disabled_at"]??null}))};}catch(e){return fail(reply,e);} });
  app.post("/admin/actions/ops/users/:id/enable", cfg("enableUser","admin.users.write"), async (request,reply)=>{try{requireActionPermission("admin.users.write");const{id}=Id.parse(request.params);const req=Confirm.parse(request.body);const old=await idempotentResult(req.idempotency_key,"enableUser");if(old)return{...old,duplicate:true};const row=await getDb().collection("cloud_users").findOne({id},{projection:{_id:0,password_hash:0}});if(!row)return reply.code(404).send({detail:"User not found."});await consumeAdminConfirmation(req.confirmation_token,"user",id,"enable",{id,disabled_at:row["disabled_at"]??null});await getDb().collection("cloud_users").updateOne({id},{$unset:{disabled_at:"",disabled_reason:""},$set:{updated_at:new Date().toISOString()}});const result={enabled:true,user_id:id};await saveIdempotentResult(req.idempotency_key,"enableUser",result);return result;}catch(e){return fail(reply,e);} });

  app.get("/admin/actions/ops/licenses", cfg("listLicenses","admin.read"), async (request)=>{ requireActionPermission("admin.read"); const q=UserLookup.parse(request.query); const filter:Record<string,unknown>={}; if(q.q)filter["$or"]=[{buyer_email:{$regex:q.q,$options:"i"}},{pin:{$regex:q.q,$options:"i"}},{mt5_account:{$regex:q.q,$options:"i"}}]; const rows=await getDb().collection("pin_licenses").find(filter,{projection:{_id:0}}).sort({created_at:-1}).limit(q.limit).toArray(); return {total_returned:rows.length,licenses:rows.map(r=>sanitizeLicense(r as Record<string,unknown>))}; });
  app.get("/admin/actions/ops/licenses/:id", cfg("getLicense","admin.read"), async (request,reply)=>{requireActionPermission("admin.read");const{id}=Id.parse(request.params);const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const history=await getDb().collection("admin_action_audit").find({target:{$regex:id}},{projection:{_id:0}}).sort({at:-1}).limit(50).toArray();return {license:sanitizeLicense(row as Record<string,unknown>),history};});
  app.post("/admin/actions/ops/licenses/:id/deactivate/prepare", cfg("prepareDeactivateLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const body=Reason.parse(request.body);const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});return {license:sanitizeLicense(row as Record<string,unknown>),reason:body.reason,...await issueAdminConfirmation("license",String(row["id"]??row["pin"]),"deactivate",{active:row["is_active"],reason:body.reason,mt5_account:row["mt5_account"]??null})};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/deactivate", cfg("deactivateLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const req=Confirm.merge(Reason).parse(request.body);const old=await idempotentResult(req.idempotency_key,"deactivateLicense");if(old)return{...old,duplicate:true};const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const target=String(row["id"]??row["pin"]);await consumeAdminConfirmation(req.confirmation_token,"license",target,"deactivate",{active:row["is_active"],reason:req.reason,mt5_account:row["mt5_account"]??null});const at=new Date().toISOString();await getDb().collection("pin_licenses").updateOne({$or:[{id},{pin:id}]},{$set:{is_active:false,revoked_at:at,revoked_reason:req.reason}});const result={deactivated:true,license_id:target,at};await saveIdempotentResult(req.idempotency_key,"deactivateLicense",result);return result;}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/activate/prepare", cfg("prepareActivateLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});return {license:sanitizeLicense(row as Record<string,unknown>),...await issueAdminConfirmation("license",String(row["id"]??row["pin"]),"activate",{active:row["is_active"],mt5_account:row["mt5_account"]??null})};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/activate", cfg("activateLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const req=Confirm.parse(request.body);const old=await idempotentResult(req.idempotency_key,"activateLicense");if(old)return{...old,duplicate:true};const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const target=String(row["id"]??row["pin"]);await consumeAdminConfirmation(req.confirmation_token,"license",target,"activate",{active:row["is_active"],mt5_account:row["mt5_account"]??null});await getDb().collection("pin_licenses").updateOne({$or:[{id},{pin:id}]},{$set:{is_active:true,reactivated_at:new Date().toISOString()},$unset:{revoked_at:"",revoked_reason:""}});const result={activated:true,license_id:target};await saveIdempotentResult(req.idempotency_key,"activateLicense",result);return result;}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/transfer/prepare", cfg("prepareTransferLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const body=Transfer.parse(request.body);const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const target=String(row["id"]??row["pin"]);return {license:sanitizeLicense(row as Record<string,unknown>),new_email:body.new_email,...await issueAdminConfirmation("license",target,"transfer",{buyer_email:row["buyer_email"],new_email:body.new_email.toLowerCase(),reason:body.reason})};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/transfer", cfg("transferLicense","admin.licenses.write"), async(request,reply)=>{try{requireActionPermission("admin.licenses.write");const{id}=Id.parse(request.params);const req=Confirm.merge(Transfer).parse(request.body);const old=await idempotentResult(req.idempotency_key,"transferLicense");if(old)return{...old,duplicate:true};const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const target=String(row["id"]??row["pin"]);await consumeAdminConfirmation(req.confirmation_token,"license",target,"transfer",{buyer_email:row["buyer_email"],new_email:req.new_email.toLowerCase(),reason:req.reason});await getDb().collection("pin_licenses").updateOne({$or:[{id},{pin:id}]},{$set:{buyer_email:req.new_email.toLowerCase(),transferred_at:new Date().toISOString(),transfer_reason:req.reason}});const result={transferred:true,license_id:target,new_email:req.new_email.toLowerCase()};await saveIdempotentResult(req.idempotency_key,"transferLicense",result);return result;}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/licenses/:id/resend-email", cfg("resendLicenseEmail","admin.email.write"), async(request,reply)=>{requireActionPermission("admin.email.write");const{id}=Id.parse(request.params);const row=await getDb().collection("pin_licenses").findOne({$or:[{id},{pin:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"License not found."});const sent=await sendPinEmail(String(row["buyer_email"]??""),String(row["buyer_name"]??""),String(row["pin"]??""));return {sent,recipient:maskEmail(row["buyer_email"])};});
  // account_notice is deliberately admin-initiated only -- there is no single deterministic system event for it (see email-system spec: "not a generic catch-all").
  app.post("/admin/actions/ops/users/:id/account-notice", cfg("sendAccountNotice","admin.email.write"), async(request,reply)=>{requireActionPermission("admin.email.write");const{id}=Id.parse(request.params);const body=AccountNotice.parse(request.body);const row=await getDb().collection("cloud_users").findOne({$or:[{id},{email:id.toLowerCase()}]},{projection:{_id:0,email:1,full_name:1}});if(!row||!row["email"])return reply.code(404).send({detail:"User not found."});const sent=await sendAccountNoticeEmail(String(row["email"]),String(row["full_name"]??""),body.subject,body.message);return {sent,recipient:maskEmail(row["email"])};});

  app.get("/admin/actions/ops/academy/certificates", cfg("listAcademyCertificates","admin.read"), async(request)=>{requireActionPermission("admin.read");const q=z.object({limit:z.coerce.number().int().min(1).max(500).optional().default(100)}).parse(request.query);const rows=await adminListCertificates(q.limit);return {total_returned:rows.length,certificates:rows};});
  app.post("/admin/actions/ops/academy/certificates/:id/revoke", cfg("revokeAcademyCertificate","admin.email.write"), async(request,reply)=>{requireActionPermission("admin.email.write");const{id}=Id.parse(request.params);const body=Reason.parse(request.body);const revoked=await adminRevokeCertificate(id,body.reason);if(!revoked)return reply.code(404).send({detail:"Certificate not found or already revoked."});await auditAdminAction(request,"revoke_academy_certificate",id,"success",{reason:body.reason});return {revoked:true,certificate_id:id};});

  app.get("/admin/actions/ops/orders", cfg("listOrders","admin.orders.read"), async(request)=>{requireActionPermission("admin.orders.read");const q=OrderLookup.parse(request.query);const filter:Record<string,unknown>={};if(q.q)filter["$or"]=[{reference:{$regex:q.q,$options:"i"}},{buyer_email:{$regex:q.q,$options:"i"}},{buyer_name:{$regex:q.q,$options:"i"}}];if(q.status)filter["payment_status"]=q.status;const rows=await getDb().collection("payment_transactions").find(filter,{projection:{_id:0}}).sort({created_at:-1}).limit(q.limit).toArray();return{total_returned:rows.length,orders:rows.map(r=>sanitizeOrder(r as Record<string,unknown>))};});
  app.get("/admin/actions/ops/orders/:id", cfg("getOrder","admin.orders.read"), async(request,reply)=>{requireActionPermission("admin.orders.read");const{id}=Id.parse(request.params);const row=await getDb().collection("payment_transactions").findOne({reference:id},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"Order not found."});return {order:sanitizeOrder(row as Record<string,unknown>),payment_status:row["payment_status"],refund_status:row["refund_status"]??"not_recorded",provider_reference:row["nomba_transaction_id"]??row["reference"]};});
  app.get("/admin/actions/ops/payments/failed", cfg("getFailedPayments","admin.orders.read"), async()=>{requireActionPermission("admin.orders.read");const rows=await getDb().collection("payment_transactions").find({payment_status:{$nin:["success","FULFILLED","PAID"]}},{projection:{_id:0}}).sort({created_at:-1}).limit(100).toArray();return{payments:rows.map(r=>sanitizeOrder(r as Record<string,unknown>))};});

  app.get("/admin/actions/ops/email/templates", cfg("listEmailTemplates","admin.email.read"), async()=>{requireActionPermission("admin.email.read");return{templates:await listTransactionalTemplates()};});
  app.get("/admin/actions/ops/email/templates/:id", cfg("getEmailTemplate","admin.email.read"), async(request)=>{requireActionPermission("admin.email.read");const{id}=Id.parse(request.params);TransactionalTemplateIdSchema.parse(id);return transactionalTemplate(id);});
  app.post("/admin/actions/ops/email/templates/:id/drafts", cfg("createTransactionalEmailDraft","admin.email.write"), async(request,reply)=>{try{requireActionPermission("admin.email.write");const{id}=Id.parse(request.params);const body=TransactionalTemplateDraftSchema.parse({...((request.body ?? {}) as Record<string, unknown>),template_id:id});const now=new Date().toISOString();await getDb().collection("transactional_email_templates").updateOne({template_id:id},{$set:{template_id:id,draft_subject:body.subject,draft_preheader:body.preheader,draft_document:body.document,updated_at:now,updated_by:"chatgpt_action"},$setOnInsert:{created_at:now}},{upsert:true});return{template_id:id,status:"draft",updated_at:now};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/email/templates/:id/preview", cfg("previewTransactionalEmail","admin.email.read"), async(request,reply)=>{try{requireActionPermission("admin.email.read");const{id}=Id.parse(request.params);const body=TemplatePreview.parse(request.body??{});const row=await getDb().collection("transactional_email_templates").findOne({template_id:id});if(!row?.["draft_document"]&&!row?.["published_document"])return reply.code(404).send({detail:"No structured draft or published override exists for this template."});const doc=(row["draft_document"]??row["published_document"]);return renderTransactional(doc as never,String(row["draft_subject"]??row["published_subject"]??"XauCloud"),String(row["draft_preheader"]??row["published_preheader"]??""),body.sample_context);}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/email/templates/:id/publish/prepare", cfg("prepareTransactionalTemplatePublish","admin.email.publish"), async(request,reply)=>{try{requireActionPermission("admin.email.publish");const{id}=Id.parse(request.params);const row=await getDb().collection("transactional_email_templates").findOne({template_id:id},{projection:{_id:0}});if(!row?.["draft_document"])return reply.code(404).send({detail:"Template draft not found."});const snapshot={template_id:id,subject:row["draft_subject"],preheader:row["draft_preheader"],document:row["draft_document"],updated_at:row["updated_at"]};return{template_id:id,live_wiring:["license_delivery","bank_transfer_instructions","bank_transfer_rejected"].includes(id),...await issueAdminConfirmation("transactional_template",id,"publish",snapshot)};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/email/templates/:id/publish", cfg("publishTransactionalTemplate","admin.email.publish"), async(request,reply)=>{try{requireActionPermission("admin.email.publish");const{id}=Id.parse(request.params);const req=Confirm.parse(request.body);const old=await idempotentResult(req.idempotency_key,"publishTransactionalTemplate");if(old)return{...old,duplicate:true};const row=await getDb().collection("transactional_email_templates").findOne({template_id:id},{projection:{_id:0}});if(!row?.["draft_document"])return reply.code(404).send({detail:"Template draft not found."});const snapshot={template_id:id,subject:row["draft_subject"],preheader:row["draft_preheader"],document:row["draft_document"],updated_at:row["updated_at"]};await consumeAdminConfirmation(req.confirmation_token,"transactional_template",id,"publish",snapshot);const version=Number(row["published_version"]??0)+1;await getDb().collection("transactional_email_template_versions").insertOne({id:`tx-template-${randomUUID()}`,template_id:id,version,subject:row["draft_subject"],preheader:row["draft_preheader"],document:row["draft_document"],published_at:new Date().toISOString(),source:"chatgpt_action"});await getDb().collection("transactional_email_templates").updateOne({template_id:id},{$set:{published_version:version,published_subject:row["draft_subject"],published_preheader:row["draft_preheader"],published_document:row["draft_document"],published_at:new Date().toISOString()}});const result={published:true,template_id:id,version};await saveIdempotentResult(req.idempotency_key,"publishTransactionalTemplate",result);return result;}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/email/templates/:id/rollback/prepare", cfg("prepareTransactionalTemplateRollback","admin.email.publish"), async(request,reply)=>{try{requireActionPermission("admin.email.publish");const{id}=Id.parse(request.params);const versions=await getDb().collection("transactional_email_template_versions").find({template_id:id},{projection:{_id:0}}).sort({version:-1}).limit(2).toArray();if(versions.length<2)return reply.code(404).send({detail:"No prior published version exists."});const target=versions[1]!;return{target_version:target["version"],...await issueAdminConfirmation("transactional_template",id,"rollback",{template_id:id,target_version:target["version"],document:target["document"]})};}catch(e){return fail(reply,e);}});
  app.post("/admin/actions/ops/email/templates/:id/rollback", cfg("rollbackTransactionalTemplate","admin.email.publish"), async(request,reply)=>{try{requireActionPermission("admin.email.publish");const{id}=Id.parse(request.params);const req=Confirm.parse(request.body);const versions=await getDb().collection("transactional_email_template_versions").find({template_id:id},{projection:{_id:0}}).sort({version:-1}).limit(2).toArray();if(versions.length<2)return reply.code(404).send({detail:"No prior published version exists."});const target=versions[1]!;await consumeAdminConfirmation(req.confirmation_token,"transactional_template",id,"rollback",{template_id:id,target_version:target["version"],document:target["document"]});await getDb().collection("transactional_email_templates").updateOne({template_id:id},{$set:{published_version:target["version"],published_subject:target["subject"],published_preheader:target["preheader"],published_document:target["document"],published_at:new Date().toISOString()}});return{rolled_back:true,template_id:id,version:target["version"]};}catch(e){return fail(reply,e);}});
  app.get("/admin/actions/ops/email/deliveries", cfg("searchEmailDeliveries","admin.email.read"), async(request)=>{requireActionPermission("admin.email.read");const q=z.object({limit:z.coerce.number().int().min(1).max(500).optional().default(100)}).parse(request.query);return emailDeliverySummary(q.limit);});

  app.get("/admin/actions/ops/system/health", cfg("getSystemHealth","admin.system.read"), async()=>{requireActionPermission("admin.system.read");const db=await getDb().command({ping:1});return{readiness:readinessSnapshot(),database:{ok:Number(db["ok"]??0)===1},time:new Date().toISOString()};});
  app.get("/admin/actions/ops/system/errors", cfg("getRecentErrors","admin.system.read"), async(request)=>{requireActionPermission("admin.system.read");const q=z.object({limit:z.coerce.number().int().min(1).max(200).optional().default(50)}).parse(request.query);return{errors:recentDiagnostics("error",q.limit)};});
  app.get("/admin/actions/ops/system/warnings", cfg("getRecentWarnings","admin.system.read"), async(request)=>{requireActionPermission("admin.system.read");const q=z.object({limit:z.coerce.number().int().min(1).max(200).optional().default(50)}).parse(request.query);return{warnings:recentDiagnostics("warning",q.limit)};});
  app.get("/admin/actions/ops/system/traces/:id", cfg("getRequestTrace","admin.system.read"), async(request)=>{requireActionPermission("admin.system.read");const{id}=Id.parse(request.params);const [memory,audit,emailAudit,marketingAudit,requestTrace]=await Promise.all([Promise.resolve(diagnosticByRequest(id)),getDb().collection("admin_action_audit").find({$or:[{request_id:id},{correlation_id:id}]},{projection:{_id:0}}).limit(50).toArray(),getDb().collection("admin_email_action_audit").find({request_id:id},{projection:{_id:0}}).limit(50).toArray(),getDb().collection("marketing_action_audit").find({request_id:id},{projection:{_id:0}}).limit(50).toArray(),getDb().collection("admin_action_request_trace").find({$or:[{request_id:id},{correlation_id:id}]},{projection:{_id:0}}).limit(50).toArray()]);return{correlation_id:id,diagnostics:memory,audit,email_audit:emailAudit,marketing_audit:marketingAudit,request_trace:requestTrace};});
  app.get("/admin/actions/ops/system/integrations", cfg("getIntegrationHealth","admin.system.read"), async()=>{requireActionPermission("admin.system.read");const raw=await getSettings();const settings=redactConfig(raw);return{database:readinessSnapshot().dependencies["database"],email:{configured:Boolean(raw["smtp_email"]&&raw["smtp_password"]),sender:settings["mail_from"]??settings["support_email"]??settings["smtp_email"]??""},push:{configured:Boolean(raw["vapid_public_key"]||raw["onesignal_app_id"])},payments:{paystack_configured:Boolean(raw["paystack_secret_key"]),nomba_configured:Boolean(raw["nomba_client_id"]&&raw["nomba_client_secret"]),note:"Secret values are never returned."}};});
  app.get("/admin/actions/ops/system/deployment", cfg("getDeploymentInfo","admin.system.read"), async()=>{requireActionPermission("admin.system.read");return{node:process.version,environment:process.env["ENVIRONMENT"]??"production",release:await releaseSummary(),started_at:readinessSnapshot().initialized_at};});
  app.get("/admin/actions/ops/audit", cfg("getAuditLogs","admin.system.read"), async(request)=>{requireActionPermission("admin.system.read");const q=z.object({limit:z.coerce.number().int().min(1).max(200).optional().default(100)}).parse(request.query);return{events:await getDb().collection("admin_action_audit").find({},{projection:{_id:0}}).sort({at:-1}).limit(q.limit).toArray()};});

  app.get("/admin/actions/ops/replays", cfg("listReplays","admin.read"), async()=>{requireActionPermission("admin.read");const d=await replayData();return{replays:[{id:"current-30-day-gold-replay",meta:d["meta"],summary:d["summary"],historical:true,guaranteed:false}]};});
  app.get("/admin/actions/ops/replays/:id", cfg("getReplay","admin.read"), async(request,reply)=>{requireActionPermission("admin.read");const{id}=Id.parse(request.params);if(id!=="current-30-day-gold-replay")return reply.code(404).send({detail:"Replay not found."});const d=await replayData();return{id,meta:d["meta"],summary:d["summary"],historical:true,guaranteed:false};});
  app.get("/admin/actions/ops/replays/:id/trades", cfg("getReplayTrades","admin.read"), async(request,reply)=>{requireActionPermission("admin.read");const{id}=Id.parse(request.params);if(id!=="current-30-day-gold-replay")return reply.code(404).send({detail:"Replay not found."});const q=z.object({offset:z.coerce.number().int().min(0).optional().default(0),limit:z.coerce.number().int().min(1).max(100).optional().default(50)}).parse(request.query);const d=await replayData();const trades=(d["trades"] as Record<string,unknown>[]??[]).map((t,i)=>({trade_id:String(i+1),trade_number:i+1,symbol:String((d["meta"] as Record<string,unknown>)?.["symbol"]??"XAUUSD"),side:t["direction"],entry_time:t["open_time"],exit_time:t["close_time"],entry_price:t["entry_price"],exit_price:t["exit_price"],stop_loss:t["stop_loss"]??null,take_profit:t["take_profit"]??null,result:t["result"],profit_loss_usd:t["profit_usd"],pips:t["pips"],gold_moves:t["gold_moves"],setup_label:t["setup"]??t["pattern"]??null,replay_id:id,historical:true}));return{total:trades.length,trades:trades.slice(q.offset,q.offset+q.limit),disclaimer:(d["meta"] as Record<string,unknown>)?.["disclaimer"]??"Historical replay; not a guarantee."};});
  app.get("/admin/actions/ops/replays/:id/trades/:tradeId", cfg("getReplayTrade","admin.read"), async(request,reply)=>{requireActionPermission("admin.read");const p=z.object({id:z.string(),tradeId:z.string()}).parse(request.params);if(p.id!=="current-30-day-gold-replay")return reply.code(404).send({detail:"Replay not found."});const d=await replayData();const idx=Number(p.tradeId)-1;const t=(d["trades"] as Record<string,unknown>[]??[])[idx];if(!t)return reply.code(404).send({detail:"Trade not found."});return{trade_id:p.tradeId,trade_number:idx+1,...t,replay_id:p.id,historical:true,guaranteed:false};});
  app.get("/admin/actions/ops/performance", cfg("getPublishedPerformance","admin.read"), async()=>{requireActionPermission("admin.read");const d=await replayData();return{published:{meta:d["meta"],summary:d["summary"]},historical:true,guaranteed:false};});

  app.get("/admin/actions/ops/releases", cfg("listReleases","admin.read"), async()=>{requireActionPermission("admin.read");const m=await loadEaReleaseManifest();return{current_version:m.current_version,releases:Object.entries(m.releases??{}).map(([version,r])=>({version,...(r as Record<string,unknown>)}))};});
  app.get("/admin/actions/ops/releases/production", cfg("getProductionRelease","admin.read"), async()=>{requireActionPermission("admin.read");return releaseSummary();});
  // POST /admin/actions/ops/releases/version-email-draft -- the "automatic bot-version
  // email system": auto-drafts a real, ready-to-review email from the CURRENT production
  // release's own release_notes (already written in customer-safe plain English at
  // promotion time -- never developer jargon), targeting the existing "active_license"
  // audience. It only ever produces a DRAFT in admin_email_drafts -- sending still goes
  // through the existing preview -> prepare-send -> confirm flow (POST /admin/actions/
  // email/drafts/:id/{preview,prepare-send,send}), so a human always reviews and approves
  // before anything reaches a customer. Idempotent per version: calling this again for a
  // version that already has a draft returns the existing draft instead of duplicating it.
  app.post("/admin/actions/ops/releases/version-email-draft", cfg("draftBotVersionEmail","admin.email.write"), async()=>{
    requireActionPermission("admin.email.write");
    const release = await releaseSummary();
    const current = release["current"] as Record<string, unknown> | null;
    if (!current) throw Object.assign(new Error("No current production release is set."), { statusCode: 409 });
    const version = String(current["version"] ?? release["current_version"] ?? "");
    const db = getDb();
    const existing = await db.collection("admin_email_drafts").findOne({ source: "bot_version_release", source_version: version }, { projection: { _id: 0 } });
    if (existing) return { ...publicDraft(existing), duplicate: true };

    const notes = String(current["release_notes"] ?? "").trim();
    const now = new Date().toISOString();
    const doc = {
      id: `draft-${randomUUID()}`,
      campaign_id: null,
      title: `Bot update ${version}`,
      subject: "A new XauCloud Bot update is available",
      preview_text: "The latest production EA is ready to download.",
      sender_name: "", reply_to: "",
      audience: "active_license",
      to: "", selected_recipients: [],
      document: {
        version: 1,
        theme: { width: 640, background: "#08080A", contentBackground: "#FFFFFF", accent: "#D6B35A", radius: 10, spacing: "normal" },
        blocks: [
          { id: `ve-hero-${randomUUID()}`, type: "hero", badge: "Production update", title: "A new XauCloud Bot update is available", subtitle: `Version ${version}` },
          { id: `ve-body-${randomUUID()}`, type: "text", html: `<p>Hi {{first_name}},</p><p>We've released a new production version of the XauCloud Bot.</p><p>${notes || "This update improves the trading engine."}</p><p>If your bot updates automatically, no action is required. Otherwise, download the latest build from Command Center and replace your current EA.</p>` },
          { id: `ve-cta-${randomUUID()}`, type: "button", text: "OPEN COMMAND CENTER", url: "https://xaucloud.io/command", style: "gold" },
          { id: `ve-risk-${randomUUID()}`, type: "risk", html: "<p>Educational tool. Trading involves risk of loss. Past or historical results do not guarantee future performance.</p>" },
        ],
      },
      source: "bot_version_release",
      source_version: version,
      created_by: "system:release_promotion",
      updated_by: "system:release_promotion",
      created_at: now, updated_at: now,
    };
    await db.collection("admin_email_drafts").insertOne({ ...doc });
    return { ...publicDraft(doc), duplicate: false };
  });
  app.get("/admin/actions/ops/bot/status", cfg("getBotStatus","admin.read"), async()=>{requireActionPermission("admin.read");const hb=await getDb().collection("cloud_bot_heartbeats").findOne({},{projection:{_id:0},sort:{ts:-1}});return{latest_heartbeat:hb??null};});
  app.get("/admin/actions/ops/bot/instances", cfg("getConnectedInstances","admin.read"), async()=>{requireActionPermission("admin.read");const rows=await getDb().collection("cloud_bot_heartbeats").aggregate([{$sort:{ts:-1}},{$group:{_id:"$pin",latest:{$first:"$$ROOT"}}},{$limit:100}]).toArray();return{instances:rows.map(r=>{const x={...(r["latest"] as Record<string,unknown>)};delete x["_id"];return x;})};});

  app.get("/admin/actions/ops/command-center/health", cfg("getCommandCenterHealth","admin.read"), async()=>{requireActionPermission("admin.read");const hb=await getDb().collection("cloud_bot_heartbeats").findOne({},{projection:{_id:0},sort:{ts:-1}});const users=await getDb().collection("cloud_users").countDocuments({});const pushes=await getDb().collection("web_push_subscriptions").countDocuments({});return{users,total_push_subscriptions:pushes,latest_bot_heartbeat:hb?.["ts"]??null,frontend_version:process.env["FRONTEND_VERSION"]??"not_exposed"};});
  app.get("/admin/actions/ops/analytics/dashboard", cfg("getDashboardMetrics","admin.analytics.read"), async()=>{requireActionPermission("admin.analytics.read");const db=getDb();const [users,licenses,activeLicenses,orders,revenue]=await Promise.all([db.collection("cloud_users").countDocuments({}),db.collection("pin_licenses").countDocuments({}),db.collection("pin_licenses").countDocuments({is_active:true}),db.collection("payment_transactions").countDocuments({}),db.collection("payment_transactions").aggregate([{$match:{payment_status:{$in:["success","FULFILLED","PAID"]}}},{$group:{_id:null,total:{$sum:"$amount_kobo"}}}]).toArray()]);return{registrations:users,licenses:{total:licenses,active:activeLicenses},orders,revenue:{currency:"NGN",amount_minor:Number(revenue[0]?.["total"]??0),amount:Number(revenue[0]?.["total"]??0)/100}};});
  app.get("/admin/actions/ops/analytics/email", cfg("getEmailPerformance","admin.analytics.read"), async()=>{requireActionPermission("admin.analytics.read");return emailDeliverySummary(200);});

  app.get("/admin/actions/ops/website/homepage", cfg("getHomepageContent","admin.read"), async()=>{requireActionPermission("admin.read");const campaigns=await getDb().collection("marketing_website_assets").find({status:"published",slot:{$in:["homepage_hero_campaign","homepage_announcement","homepage_performance_feature","homepage_promo_banner"]}},{projection:{_id:0}}).toArray();return{live_campaigns:campaigns,source:"controlled marketing slots; static React copy is not exposed as arbitrary filesystem access"};});
  app.get("/admin/actions/ops/website/pricing", cfg("getPricingContent","admin.read"), async()=>{requireActionPermission("admin.read");const s=await getSettings();return{price_minor:Number(s["pin_price_kobo"]??0),currency:"NGN",purchase_url:`${process.env["PUBLIC_SITE_URL"]??"https://xaucloud.io"}/#purchase`};});
  app.get("/admin/actions/ops/website/performance", cfg("getPerformancePageContent","admin.read"), async()=>{requireActionPermission("admin.read");const d=await replayData();return{meta:d["meta"],summary:d["summary"],historical:true,guaranteed:false};});
  app.get("/admin/actions/ops/website/announcements", cfg("getLiveAnnouncement","admin.read"), async()=>{requireActionPermission("admin.read");return{announcements:await getDb().collection("marketing_announcements").find({status:"published"},{projection:{_id:0}}).sort({published_at:-1}).limit(20).toArray()};});
  app.get("/admin/actions/ops/website/landing-pages/:id", cfg("getLandingPageContent","admin.read"), async(request,reply)=>{requireActionPermission("admin.read");const{id}=Id.parse(request.params);const row=await getDb().collection("marketing_landing_pages").findOne({$or:[{id},{slug:id}]},{projection:{_id:0}});if(!row)return reply.code(404).send({detail:"Landing page not found."});return row;});

  app.get("/admin/actions/ops/support/tickets", cfg("listSupportTickets","admin.read"), async(request)=>{requireActionPermission("admin.read");const q=UserLookup.parse(request.query);const rows=await getDb().collection("support_tickets").find({},{projection:{_id:0,customer_private_notes:0}}).sort({updated_at:-1}).limit(q.limit).toArray();return{available:rows.length>0,tickets:rows,note:rows.length?undefined:"No support ticket records currently exist in this backend."};});
  app.get("/admin/actions/ops/support/tickets/:id", cfg("getSupportTicket","admin.read"), async(request,reply)=>{requireActionPermission("admin.read");const{id}=Id.parse(request.params);const row=await getDb().collection("support_tickets").findOne({id},{projection:{_id:0,customer_private_notes:0}});if(!row)return reply.code(404).send({detail:"Support ticket not found."});return row;});
  app.post("/admin/actions/ops/support/tickets/:id/reply-drafts", cfg("createSupportReplyDraft","admin.support.write"), async(request,reply)=>{requireActionPermission("admin.support.write");const{id}=Id.parse(request.params);const body=TicketDraft.parse(request.body);const ticket=await getDb().collection("support_tickets").findOne({id},{projection:{_id:0}});if(!ticket)return reply.code(404).send({detail:"Support ticket not found."});const draft={id:`support-draft-${randomUUID()}`,ticket_id:id,body:body.body,status:"draft",created_at:new Date().toISOString(),source:"chatgpt_action"};await getDb().collection("support_reply_drafts").insertOne(draft);return draft;});

  app.get("/admin/actions/ops/notifications", cfg("listNotifications","admin.read"), async(request)=>{requireActionPermission("admin.read");const q=z.object({limit:z.coerce.number().int().min(1).max(200).optional().default(50)}).parse(request.query);const [push,ann]=await Promise.all([getDb().collection("marketing_push_delivery_log").find({},{projection:{_id:0}}).sort({at:-1}).limit(q.limit).toArray(),getDb().collection("marketing_announcements").find({},{projection:{_id:0}}).sort({created_at:-1}).limit(q.limit).toArray()]);return{push_history:push,announcement_history:ann};});
}

export { ensureAdminOpsInfrastructure };
