import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { getDb } from "../../db.js";
import { requireAdmin } from "../../auth.js";
import { sendEmail } from "../../services/email.js";
import { emailBranding } from "../../services/emailBranding.js";
import { renderBroadcastEmail } from "../../services/broadcastEmail.js";

// Admin email console: compose + send a message to a single address or
// broadcast it to every registered customer (cloud_users). Sending always
// goes through the shared SMTP sender (services/email), so it honours whatever
// provider the admin configured (Gmail or Hostinger support@xaucloud.io).
// A broadcast requires an explicit confirm flag; every send is logged.

const BROADCAST_CAP = 5000; // safety ceiling for a single broadcast

const SendSchema = z.object({
  mode: z.enum(["single", "broadcast"]),
  to: z.string().nullable().optional(),
  subject: z.string().min(1).max(300),
  body_html: z.string().min(1).max(200_000),
  preview_text: z.string().max(300).nullable().optional(),
  cta_label: z.string().max(80).nullable().optional(),
  cta_url: z.string().url().max(2000).nullable().optional(),
  confirm: z.boolean().nullable().optional(),
});

const TestSchema = z.object({
  subject: z.string().min(1).max(300),
  body_html: z.string().min(1).max(200_000),
  preview_text: z.string().max(300).nullable().optional(),
  cta_label: z.string().max(80).nullable().optional(),
  cta_url: z.string().url().max(2000).nullable().optional(),
  to: z.string().nullable().optional(),
});

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function render(req: { body_html: string; preview_text?: string | null; cta_label?: string | null; cta_url?: string | null }, branding: Awaited<ReturnType<typeof emailBranding>>): string {
  return renderBroadcastEmail({
    bodyHtml: req.body_html,
    previewText: req.preview_text,
    ctaLabel: req.cta_label,
    ctaUrl: req.cta_url,
  }, branding);
}

async function broadcastRecipients(): Promise<string[]> {
  const db = getDb();
  const rows = await db
    .collection("cloud_users")
    .find({ email: { $exists: true, $ne: "" } }, { projection: { _id: 0, email: 1 } })
    .toArray();
  const seen = new Set<string>();
  const out: string[] = [];
  for (const r of rows) {
    const e = String(r["email"] ?? "").trim().toLowerCase();
    if (e && EMAIL_RE.test(e) && !seen.has(e)) {
      seen.add(e);
      out.push(e);
    }
  }
  return out;
}

export async function registerAdminEmailRoutes(app: FastifyInstance): Promise<void> {
  // How many people a broadcast would reach.
  app.get("/admin/email/audience", { preHandler: requireAdmin }, async () => {
    const recipients = await broadcastRecipients();
    return { total: recipients.length, cap: BROADCAST_CAP };
  });

  // The admin preview is generated by the exact same renderer used for real
  // recipients, preventing the compose UI from drifting from delivered mail.
  app.post("/admin/email/preview", { preHandler: requireAdmin }, async (request) => {
    const req = TestSchema.omit({ to: true }).parse(request.body ?? {});
    const branding = await emailBranding();
    return { html: render(req, branding) };
  });

  // Send a test copy to the admin (or an explicit address) — never customers.
  app.post("/admin/email/test", { preHandler: requireAdmin }, async (request, reply) => {
    const req = TestSchema.parse(request.body ?? {});
    const admin = (request as typeof request & { admin: Record<string, unknown> }).admin;
    const branding = await emailBranding();
    const to = String(req.to ?? admin["email"] ?? branding.admin_notification_email ?? "").trim().toLowerCase();
    if (!EMAIL_RE.test(to)) return reply.code(400).send({ detail: "No valid test recipient (set an admin email first)." });
    const html = render(req, branding);
    const ok = await sendEmail(to, `[TEST] ${req.subject}`, html);
    if (!ok) return reply.code(502).send({ detail: "Send failed — check SMTP settings (host/port/login/password)." });
    return { sent: true, to };
  });

  // Send for real: one recipient, or a confirmed broadcast to all customers.
  app.post("/admin/email/send", { preHandler: requireAdmin }, async (request, reply) => {
    const req = SendSchema.parse(request.body ?? {});
    const admin = (request as typeof request & { admin: Record<string, unknown> }).admin;
    const branding = await emailBranding();
    const html = render(req, branding);

    let recipients: string[];
    if (req.mode === "single") {
      const to = String(req.to ?? "").trim().toLowerCase();
      if (!EMAIL_RE.test(to)) return reply.code(400).send({ detail: "Enter a valid recipient email." });
      recipients = [to];
    } else {
      if (req.confirm !== true) return reply.code(400).send({ detail: "Broadcast requires explicit confirmation." });
      recipients = await broadcastRecipients();
      if (recipients.length === 0) return reply.code(400).send({ detail: "No customers with a valid email to send to." });
      if (recipients.length > BROADCAST_CAP) recipients = recipients.slice(0, BROADCAST_CAP);
    }

    let sent = 0;
    let failed = 0;
    for (const to of recipients) {
      // eslint-disable-next-line no-await-in-loop -- intentionally sequential to stay gentle on the SMTP provider
      const ok = await sendEmail(to, req.subject, html);
      if (ok) sent += 1;
      else failed += 1;
    }

    const record = {
      at: new Date().toISOString(),
      admin_email: String(admin["email"] ?? ""),
      mode: req.mode,
      subject: req.subject,
      recipients: recipients.length,
      sent,
      failed,
    };
    try {
      await getDb().collection("admin_email_log").insertOne({ ...record });
    } catch {
      /* logging must never fail the send result */
    }

    if (sent === 0) return reply.code(502).send({ detail: "No emails were sent — check SMTP settings.", ...record });
    return record;
  });

  // Recent send history for the console.
  app.get("/admin/email/log", { preHandler: requireAdmin }, async () => {
    const rows = await getDb()
      .collection("admin_email_log")
      .find({}, { projection: { _id: 0 } })
      .sort({ at: -1 })
      .limit(20)
      .toArray();
    return { entries: rows };
  });
}
