import { z } from "zod";

/** Port of server.py:4377 `class PositionCheckRequest(BaseModel)`. */
export const PositionCheckRequestSchema = z.object({
  pin: z.string().optional().default(""),
  account_id: z.string().optional().default(""),
  symbol: z.string().optional().default("XAUUSD"),
  direction: z.string().optional().default(""),
  entry_price: z.number().optional().default(0),
  current_price: z.number().optional().default(0),
  profit: z.number().optional().default(0),
  lots: z.number().optional().default(0),
  rsi: z.number().optional().default(0),
  ema_fast: z.number().optional().default(0),
  ema_slow: z.number().optional().default(0),
  atr: z.number().optional().default(0),
  minutes_open: z.number().optional().default(0),
  sl: z.number().optional().default(0),
  tp: z.number().optional().default(0),
  thesis: z.string().optional().default(""),
  invalidation: z.string().optional().default(""),
  confidence: z.number().optional().default(0),
  peak_profit: z.number().optional().default(0),
  pending_exit_reason: z.string().optional().default(""),
  regime: z.string().optional().default(""),
  r_mult: z.number().optional().default(0),
  htf_consensus: z.string().optional().default("NEUTRAL"),
  session: z.string().optional().default(""),
  setup_name: z.string().optional().default(""),
  daily_pct: z.number().optional().default(0),
  open_positions: z.number().optional().default(1),
});
export type PositionCheckRequest = z.infer<typeof PositionCheckRequestSchema>;

/** Port of server.py:4569 `class AIAnalysisRequest(BaseModel)`. */
export const AIAnalysisRequestSchema = z.object({
  pin: z.string().optional().default(""),
  account_id: z.string().optional().default(""),
  symbol: z.string().optional().default("XAUUSD"),
  ema_fast: z.number().optional().default(0),
  ema_slow: z.number().optional().default(0),
  rsi: z.number().optional().default(0),
  stoch: z.number().optional().default(50.0),
  mom: z.number().optional().default(0.0),
  atr: z.number().optional().default(0),
  price: z.number().optional().default(0),
  h1_trend: z.string().optional().default("FLAT"),
  spread: z.number().optional().default(0),
  recent_candles: z.string().optional().default(""),
  setup: z.string().optional().default(""),
  regime: z.string().optional().default(""),
  signature: z.string().optional().default(""),
  htf_consensus: z.string().optional().default("NEUTRAL"),
  session: z.string().optional().default(""),
  session_quality: z.number().optional().default(1.0),
  open_positions: z.number().optional().default(0),
  basket_float_pl: z.number().optional().default(0.0),
  recent_wins: z.number().optional().default(0),
  recent_losses: z.number().optional().default(0),
  account_equity: z.number().optional().default(0.0),
  daily_pct: z.number().optional().default(0.0),
  grade: z.string().optional().default(""),
  setup_score: z.number().optional().default(0.0),
  combined_score: z.number().optional().default(0.0),
});
export type AIAnalysisRequest = z.infer<typeof AIAnalysisRequestSchema>;

/** Port of server.py:4602 `class TradeMemoryRecord(BaseModel)` (extra="ignore" -- unknown fields dropped, matched by .passthrough() being absent). */
export const TradeMemoryRecordSchema = z.object({
  event: z.string().optional().default("CLOSE"),
  pin: z.string().optional().default(""),
  time: z.string().optional().default(""),
  account: z.string().optional().default(""),
  broker: z.string().optional().default(""),
  ea_version: z.string().optional().default(""),
  build_hash: z.string().optional().default(""),
  input_hash: z.string().optional().default(""),
  symbol: z.string().optional().default("XAUUSD"),
  timeframe: z.string().optional().default("M10"),
  magic_number: z.number().optional().default(0),
  session: z.string().optional().default(""),
  strategy: z.string().optional().default(""),
  direction: z.string().optional().default(""),
  entry_price: z.number().optional().default(0.0),
  exit_price: z.number().optional().default(0.0),
  lot_size: z.number().optional().default(0.0),
  grade: z.string().optional().default(""),
  confidence: z.number().optional().default(0),
  market_regime: z.string().optional().default(""),
  news_state: z.string().optional().default(""),
  spread_state: z.string().optional().default(""),
  spread_points: z.number().optional().default(0.0),
  htf_trend: z.string().optional().default(""),
  m1_confirm: z.string().optional().default(""),
  m5_confirm: z.string().optional().default(""),
  m15_confirm: z.string().optional().default(""),
  m30_confirm: z.string().optional().default(""),
  h1_confirm: z.string().optional().default(""),
  entry_reason: z.string().optional().default(""),
  exit_reason: z.string().optional().default(""),
  max_floating_profit: z.number().optional().default(0.0),
  max_floating_loss: z.number().optional().default(0.0),
  profit_at_close: z.number().optional().default(0.0),
  profit_left_after_exit: z.number().optional().default(0.0),
  risk_avoided_after_exit: z.number().optional().default(0.0),
  entry_quality: z.string().optional().default(""),
  exit_quality: z.string().optional().default(""),
  lot_quality: z.string().optional().default(""),
  should_hold_longer: z.boolean().optional().default(false),
  should_close_earlier: z.boolean().optional().default(false),
  what_ai_should_remember: z.string().optional().default(""),
  block_reason: z.string().optional().default(""),
  checkpoint_min: z.number().optional().default(0),
  would_trade_have_won: z.boolean().optional().default(false),
  would_trade_have_lost: z.boolean().optional().default(false),
});
export type TradeMemoryRecord = z.infer<typeof TradeMemoryRecordSchema>;
