import { createHash, randomUUID } from "node:crypto";
import { getDb } from "../db.js";
import { env } from "../env.js";

export type FinalTrade = Record<string, unknown>;
const asNumber = (v: unknown) => typeof v === "number" ? v : typeof v === "string" && v.trim() ? Number(v) : Number.NaN;
export function normalizePublicSymbol(symbol: unknown): string { return /^XAUUSD(?:[._A-Z0-9-]+)?$/i.test(String(symbol ?? "").trim()) ? "XAUUSD" : String(symbol ?? "").trim().toUpperCase().slice(0, 32); }
export function canonicalTradeId(t: FinalTrade): string { return String(t["trade_identity"] ?? t["id"] ?? `${String(t["account_login"] ?? "")}:${String(t["ticket"] ?? t["deal_id"] ?? "")}`); }
export function buildXTradePost(t: FinalTrade): string {
  // The EA's durable journal schema calls its close quote `price`; older
  // reconciled rows used close_price/exit_price.  Entry must never borrow that
  // close quote, otherwise an incomplete trade could be posted as a fake zero move.
  const profit = asNumber(t["profit"]); const entry = asNumber(t["entry_price"] ?? t["open_price"]); const exit = asNumber(t["exit_price"] ?? t["close_price"] ?? t["price"]); const dir = String(t["direction"] ?? "").toUpperCase();
  if (!t["closed"] && !t["closed_at"]) throw new Error("Only a final closed trade can be posted.");
  if (!Number.isFinite(profit) || !Number.isFinite(entry) || !Number.isFinite(exit) || !["BUY", "SELL"].includes(dir)) throw new Error("Final closed trade data is incomplete.");
  const result = profit > 0 ? "WIN" : profit < 0 ? "LOSS" : "BREAKEVEN";
  return `XauCloud Trade Closed 🟡\n\n${normalizePublicSymbol(t["symbol"])} • ${dir}\nEntry: ${entry.toFixed(2)}\nExit: ${exit.toFixed(2)}\n\nResult: ${result}\nP/L: ${profit >= 0 ? "+" : "-"}$${Math.abs(profit).toFixed(2)}\n\nAutomatically recorded by XauCloud.\nWins and losses are both published.\n\nXauCloud — Built for Gold.`;
}
export function xPostingConfigured(): boolean { return Boolean(env.X_USER_ACCESS_TOKEN); }
export async function xPostingSettings(): Promise<Record<string, unknown>> { const row = await getDb().collection("x_posting_settings").findOne({ id: "trade_posts" }, { projection: { _id: 0 } }); return { auto_post_enabled: Boolean(row?.["auto_post_enabled"]), post_wins: row?.["post_wins"] !== false, post_losses: row?.["post_losses"] !== false, post_breakeven: Boolean(row?.["post_breakeven"]), configured: xPostingConfigured(), account_username: env.X_ACCOUNT_USERNAME || null }; }
export async function enqueueFinalTradeForXPost(trade: FinalTrade): Promise<void> { const id = canonicalTradeId(trade); if (!id || id.endsWith(":")) return; const key = `x_trade_post:${id}`; await getDb().collection("x_trade_posts").updateOne({ idempotency_key: key }, { $setOnInsert: { id: `xpost-${randomUUID()}`, idempotency_key: key, closed_trade_id: id, trade, status: "queued", retry_count: 0, created_at: new Date().toISOString() } }, { upsert: true }); }
async function postToX(text: string): Promise<{ id: string }> { const response = await fetch("https://api.x.com/2/tweets", { method: "POST", headers: { Authorization: `Bearer ${env.X_USER_ACCESS_TOKEN}`, "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); const payload = await response.json().catch(() => ({})) as Record<string, unknown>; if (!response.ok) { const e = Object.assign(new Error(`X API request failed (${response.status}).`), { status: response.status, retry_after: response.headers.get("retry-after") }); throw e; } const id = String((payload["data"] as Record<string, unknown> | undefined)?.["id"] ?? ""); if (!id) throw new Error("X API did not return a post id."); return { id }; }
export async function publishApprovedXTrade(trade: FinalTrade): Promise<Record<string, unknown>> { if (!xPostingConfigured()) throw Object.assign(new Error("X user-context credentials are not configured."), { statusCode: 503 }); const snapshot = xTradePostSnapshot(trade); const key = `x_trade_post:${snapshot.closed_trade_id}`; const coll = getDb().collection("x_trade_posts"); await coll.updateOne({ idempotency_key: key }, { $setOnInsert: { id: `xpost-${randomUUID()}`, idempotency_key: key, closed_trade_id: snapshot.closed_trade_id, trade, status: "queued", retry_count: 0, created_at: new Date().toISOString(), source: "admin_manual" } }, { upsert: true }); const claimed = await coll.findOneAndUpdate({ idempotency_key: key, status: { $in: ["queued", "failed"] } }, { $set: { status: "posting", attempted_at: new Date().toISOString(), trade } }, { returnDocument: "after" }); if (!claimed) { const existing = await coll.findOne({ idempotency_key: key }, { projection: { _id: 0 } }); return { ...(existing ?? {}), duplicate: true }; } try { const posted = await postToX(snapshot.post_text); const result = { status: "posted", x_post_id: posted.id, posted_at: new Date().toISOString() }; await coll.updateOne({ idempotency_key: key, status: "posting" }, { $set: result }); return { ...result, closed_trade_id: snapshot.closed_trade_id }; } catch (error) { await failXTradePost(claimed); throw error; } }
async function failXTradePost(row: Record<string, unknown>): Promise<void> { const retries = Number(row["retry_count"] ?? 0) + 1; const retryAfter = Number((row["retry_after"] ?? 0)); const delay = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : Math.min(3600, 30 * 2 ** retries); await getDb().collection("x_trade_posts").updateOne({ idempotency_key: String(row["idempotency_key"] ?? ""), status: "posting" }, { $set: { status: retries >= 5 ? "failed" : "queued", retry_count: retries, attempted_at: new Date().toISOString(), next_attempt_at: new Date(Date.now() + delay * 1000).toISOString(), failure_reason: `X posting failed; retryable=${retries < 5}` } }); }
export async function processQueuedXTradePosts(limit = 20): Promise<void> { const settings = await xPostingSettings(); if (!settings["auto_post_enabled"] || !xPostingConfigured()) return; const coll = getDb().collection("x_trade_posts"); const now = new Date().toISOString(); const rows = await coll.find({ status: "queued", retry_count: { $lt: 5 }, $or: [{ next_attempt_at: { $exists: false } }, { next_attempt_at: { $lte: now } }] }).limit(limit).toArray(); for (const row of rows) { const trade = row["trade"] as FinalTrade; const profit = asNumber(trade["profit"]); if ((profit > 0 && !settings["post_wins"]) || (profit < 0 && !settings["post_losses"]) || (profit === 0 && !settings["post_breakeven"])) continue; const rateSlot = await getDb().collection("x_posting_settings").updateOne({ id: "trade_posts", auto_post_enabled: true, $or: [{ last_auto_post_at: { $exists: false } }, { last_auto_post_at: { $lte: new Date(Date.now() - 15_000).toISOString() } }] }, { $set: { last_auto_post_at: now } }); if (!rateSlot.modifiedCount) break; const claimed = await coll.findOneAndUpdate({ _id: row["_id"], status: "queued" }, { $set: { status: "posting", attempted_at: new Date().toISOString() } }, { returnDocument: "after" }); if (!claimed) continue; try { const posted = await postToX(buildXTradePost(trade)); await coll.updateOne({ _id: row["_id"], status: "posting" }, { $set: { status: "posted", x_post_id: posted.id, posted_at: new Date().toISOString(), attempted_at: new Date().toISOString() } }); } catch (error) { const retryAfter = Number((error as { retry_after?: unknown }).retry_after ?? 0); await failXTradePost({ ...claimed, retry_after: retryAfter }); } } }
export const xTradePostSnapshot = (trade: FinalTrade) => ({ closed_trade_id: canonicalTradeId(trade), post_text: buildXTradePost(trade), content_hash: createHash("sha256").update(buildXTradePost(trade)).digest("hex") });
